### PR TITLE
Deadline counter component

### PR DESCRIPTION
**Pull request by clementf2b**
This is component for user to see the difference between deadline and the current time.

### CODE REVIEW

**Comment by BrianSo** [comment]
Hi, It seems you have not write enough unit test for your component. Please add it back 😄

**Comment by BrianSo** [comment]
Error: Cannot find module "src/components/CountDown"
  at webpack:///test/unit/specs/CountDown.spec.js:2:0 <- index.js:12825

You misspell `Countdown` with `CountDown`. Please check before you commit and push.

**Comment by clementf2b** [comment]
Don't know how to test the sweet alert 2. Can I skip that part?

**Comment by clementf2b** [comment]
Don't know how to test the sweet alert 2 and other test is successful. Can I skip that test?

**Review by BrianSo — APPROVED** [review]
Alright

**Review by BrianSo — CHANGES_REQUESTED** [review]
Please update new changes from 'develop' to your feature first

**Review by BrianSo — APPROVED** [review]

**Pull request merged**
